name: Deploy to github pages
on:
  push:
    branches: [main]
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "filipecalegario" && git config user.email "filipe.calegario@gmail.com"
          npm run gh-pages-deploy
